# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bosdk}
  s.version = "1.1.0"
  s.platform = %q{universal-java-1.6}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shane Emmons"]
  s.date = %q{2010-04-07}
  s.default_executable = %q{boirb}
  s.description = %q{A JRuby wrapper for the Business Objects Java SDK}
  s.email = %q{semmons99@gmail.com}
  s.executables = ["boirb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/boirb",
     "bosdk.gemspec",
     "lib/bosdk.rb",
     "lib/bosdk/enterprise_session.rb",
     "lib/bosdk/info_object.rb",
     "lib/bosdk/webi_instance.rb",
     "lib/bosdk/webi_report_engine.rb",
     "spec/bosdk_spec.rb",
     "spec/enterprise_session_spec.rb",
     "spec/info_object_spec.rb",
     "spec/webi_instance_spec.rb",
     "spec/webi_report_engine_spec.rb"
  ]
  s.homepage = %q{http://semmons99.github.com/bosdk}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["An environment variable 'BOE_JAVA_LIB' pointing to the Business Objects Java SDK directory"]
  s.rubyforge_project = %q{bosdk}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{JRuby Business Object Java SDK wrapper}
  s.test_files = [
    "spec/bosdk_spec.rb",
     "spec/enterprise_session_spec.rb",
     "spec/info_object_spec.rb",
     "spec/webi_instance_spec.rb",
     "spec/webi_report_engine_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<yard>, [">= 0.5.4"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<yard>, [">= 0.5.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<yard>, [">= 0.5.4"])
  end
end

